# Generated by Django 3.1.3 on 2020-12-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaplay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faixa',
        ),
    ]
