# Generated by Django 3.1.3 on 2020-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaplay', '0003_faixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='letra',
            field=models.TextField(blank=True),
        ),
    ]
